### ISSUE TITLE
Mods won't load on Linux Mint 20 (Steam)

### ISSUE THREAD

**Issue by cor9957** [satisfactorymodding/SatisfactoryModManager#72]
Hi,

Mods won't load on Linux Mint 20, I've added the debug files.
I guess I'm doing something wrong, but I don't know what.

[SMMDebug_2020-11-16_10-34-4.zip](https://github.com/satisfactorymodding/SatisfactoryModManager/files/5545684/SMMDebug_2020-11-16_10-34-4.zip)

**Comment by mircearoata** [comment]
See https://github.com/satisfactorymodding/SatisfactoryModManager/pull/70#issuecomment-726290723

**Comment by mircearoata** [comment]
Fixed in v2.3.0

**Comment by cor9957** [comment]
I don't know if this is the way to go or that I should open a new issue, but it still isn't working.
I've added the debug files
[SMMDebug_2020-11-27_5-9-44.zip](https://github.com/satisfactorymodding/SatisfactoryModManager/files/5606081/SMMDebug_2020-11-27_5-9-44.zip)

**Comment by mircearoata** [comment]
Ah, this is the other issue that isn't SMM's fault. Somehow the bootstrapper doesn't find the game install root (it literally goes to the parent folder until it finds a folder named FactoryGame, not sure how that fails).
Download the attachment from the comment on this PR https://github.com/satisfactorymodding/SatisfactoryModBootstrapper/pull/5 and copy the dll to `~/.cache/SatisfactoryModManager/bootstrapperVersions/2.0.11` then switch to the vanilla profile and back to modded for SMM to use the bootstrapper from cache that you overwritten

**Comment by cor9957** [comment]
I'm afraid I still can't get it to work.
I'll try removing and install Satisfactory maybe that does the trick. 
Should I start Satisfactory-Mod-Manager.AppImage from a specific location, I start it now from the Desktp
Anyway thanks for your help, if I don't get it working I'll just play the vanilla version :-(

Cor.

**Comment by cor9957** [comment]
I've re-installed Steam and Satisfactory completely, but it didn't work, I guess I'll keep playing vanilla.
Again, thank you very much for your help, it is much appreciated!

Cor.

**Comment by mircearoata** [comment]
It doesn't matter where you use the appimage from

You can also try downloading the dll from the PR directly to `somewhere/Satisfactory/FactoryGame/Binaries/Win64`, and if that doesn't work either and the dlloverrides are set in Steam, I'm out of ideas

**Comment by jonasclaes** [comment]
I use my own DLL satisfactorymodding/SatisfactoryModBootstrapper/pull/5, together with these launch options in Steam: `WINEDLLOVERRIDES="msdia140.dll,xinput1_3.dll=n,b;msdia140.dll,xinput1_3.dll=n,b;msdia140.dll,xinput1_3.dll=n,b" %command%`. If you know where you installed the game, you could share your log file with us.

**Comment by bj0** [comment]
I still get this in 2.3.1

Note, the downloaded file workaround works, but the directory in the comment above is incorrect, I had to use:

> ~/.cache/SatisfactoryModManager/downloadCache/bootstrapperVersions/2.0.11
